services:
  - type: web
    name: hombre-uid-gateway
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MASTER_API_URL
        sync: false
      - key: MASTER_API_KEY
        sync: false
      - key: DEFAULT_PREFIX
        value: HOMBRE
      - key: ADMIN_PASSWORD
        sync: false
